config/routes.rb
Rails.application.routes.draw do
  get 'title_holders/index'
  get 'title_holders/show'
  get 'title_holders/new'
  get 'title_holders/edit'
  # サークル案内メニュー
  root 'welcome#index'

  resources :rating_distributions

  get 'circle_history'      => 'welcome#circle_history'
  get 'relay_shogi'         => 'welcome#relay_shogi'
  get 'circle_rule'         => 'welcome#circle_rule'
  get 'regular_meeting'     => 'welcome#regular_meeting'
  get 'faq'                 => 'welcome#faq'
  get 'faq_old'             => 'welcome#faq_old'
  get 'administration_rule' => 'welcome#administration_rule'
  get 'zainin_kikan'        => 'welcome#zainin_kikan'
  get 'join_us_information' => 'welcome#join_us_information'

  get 'usage'               => 'welcome#usage' # 利用方法

  # 会員名簿
  resources :users do
    resource :profile, only: [:new, :create, :show, :edit, :update]
  end
  # 順位
  resources :rankings

  # 研究会メニュー
  get 'laboratory'                      => 'laboratory#index'
  get 'laboratory/comment_kifu'         => 'laboratory#comment_kifu'
  get 'laboratory/gather'               => 'laboratory#gather'
  get 'laboratory/four_file_rook'       => 'laboratory#four_file_rook'
  get 'laboratory/right_king'           => 'laboratory#right_king'
  get 'laboratory/old_bbs'              => 'laboratory#old_bbs'
  get 'laboratory/particular_positions' => 'laboratory#particular_positions'
  get 'laboratory/migishiken'           => 'laboratory#migishiken'
  get 'laboratory/outline'              => 'laboratory#outline'

  resources :kifus do
    member do
      get 'json'
      get 'download'
      get 'downloads'
    end
  end

  # 棋戦メニュー
  get 'kisens/information'  => 'kisens#information'
  get 'kisens/common_rule' => 'kisens#common_rule'
  get 'kisens/handicap'    => 'kisens#handicap', as: :handicap
  resources :kisens do
    # resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
    # resource :card
  end
  resources :matchups do
    # resources :games, only: [:update]
  end
  # get 'game_dates'      => 'games#index'

  # 案内文
  resources :carousels
  resources :information, only: [:edit, :update]

  # 掲示板トップ
  get 'bbs' => 'bbs#index'
  resources :topics do
    resources :posts
  end

  # リンクメニュー
  resources :links, only: [:index, :new, :create, :update, :destroy]
  get   'links/edit'          => 'links#edit', as: :edit_links
  patch 'links/:link_id/sort' => 'links#sort', as: :link_sort

  # 会員登録・ログイン・ログアウトなど
  resources :sessions, only: [:new, :create, :destroy]
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # password resets
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 会員登録
  get  'sign_up'      => 'sign_up#new'
  post 'sign_up'      => 'sign_up#create'
  get  'registration' => 'registration#edit'
  post 'registration' => 'registration#update'

  # メールアドレスの確認
  get  'activation/:id' => 'registration#activation',     as: :activation

  # 入会承認/却下
  get 'approbation/:id' => 'account_approbation#approve', as: :approbation
  get 'rejection/:id'   => 'account_approbation#reject',  as: :rejection

  # 称号保持者
  resources :title_holders

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/topic.rb
# Topic （板、スレッド）
class Topic < ApplicationRecord
  # before_save :han_to_zen
  has_many    :posts, dependent: :destroy, inverse_of: :topic

  # 子も同時にnew, create可能に。
  accepts_nested_attributes_for :posts, allow_destroy: true

  default_scope          -> { order(updated_at: :desc) }
  # permission は、administrator / committee / everyone の三種類がある
  scope :committee,      -> { where(permission: %i(committee everyone)) }
  scope :committee_only, -> { find_by(permission: %i(committee)) }
  scope :everyone,       -> { where(permission: :everyone) }

  validates :title, length: { maximum: 50 }, presence: true

  # 画像投稿時に「ファイルを選択」ボタンの#idを一意に設定する
  def uniq_post_picture_id
    count = Post.where(topic_id: id).maximum(:post_number) || 0
    "picture_#{id}_#{count}".to_sym
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    %w(id title created_at updated_at)
  end

  private

  # 半角を全角に変換
  def han_to_zen
    require 'moji'
    self.title = Moji.normalize_zen_han(self.title.encode('utf-8'))
  end
end

app/controllers/topics_controller.rb
# トピック（掲示板スレッド）
class TopicsController < ApplicationController
  include Pagy::Backend

  before_action :enough_authority, only: [:edit, :destroy]
  before_action :logged_in_user,   only: [:new, :create]
  helper_method :enough_authority?

  def index
    @pagy, @topics = pagy(Topic.everyone)

    @enough_authority = enough_authority?
  end

  def show
    # リレー掲示板のみ Basic認証
    # basic_authentication if params[:id].to_i == 26
    @topic = if committee_user?
               Topic.includes(:posts).committee.find(params[:id])
             else
               Topic.includes(:posts).everyone.find(params[:id])
             end

    @pagy, @posts = pagy(@topic.posts.progenitor)
  end

  def new
    @topic = Topic.new
  end

  def create
    # ネストされたモデル
    # http://qiita.com/hmuronaka/items/580b977834d4b3010454
    @topic = Topic.new(topic_params)
    @post  = @topic.posts.build(post_params)
    # 添付ファイル確認
    if params[:upload_file].present?
      filename  = params[:upload_file].original_filename
      extension = File.extname(filename)
      if extension.in? ['.kif']
        # 添付ファイルが棋譜だったら
        require 'kconv'
        raw_kifu = params[:upload_file].read.toutf8
        @post[:comment] << NEWLINE << raw_kifu
        # (文字コードutf-8で「あいうえお」と書かれたファイルがアップされた場合)
        # => "\xE3\x81\x82\xE3\x81\x84\xE3\x81\x86\xE3\x81\x88\xE3\x81\x8A\n"
        # (文字コードshift_jisで「あいうえお」と書かれたファイルがアップされた場合)
        # => "\x82\xA0\x82\xA2\x82\xA4\x82\xA6\x82\xA8\n"
      elsif extension.in? ['.gif', '.jpeg', '.jpg', '.png']
        # 添付ファイルが画像だったら、
        @post.destroy # 先に生成した@postを破棄
        params[:topic][:post][:picture] = params[:upload_file]
        @post = @topic.posts.build(post_params)
      end
    end
    @topic.permission = 'everyone'
    @post.name        = current_user.name
    @post.post_number = 1
    @post.owner_id    = current_user.id
    @post.roots       = 'progenitor'

    if @topic.valid?
      @topic.save
      flash[:success] = "新規スレッドを作成しました"
      redirect_to bbs_path
    else
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    store_location
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      flash[:success] = "更新しました"
      redirect_to session[:return_to] || topics_path
    else
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy!
    flash[:success] = "削除しました"
    redirect_to bbs_path
  end

  def enough_authority?
    topic = Topic.find_by(id: params[:id])
    return false if topic.nil?
    logged_in_user? && current_user&.all_posts_owner?(topic) || admin_user?
  end

  private

  def topic_params
    # posts_attributes, post_attributes, どちらでもよい
    params.require(:topic).permit(:title, :permission, posts_attributes: [:id, :topic_id, :comment, :post_number, :owner_id, :picture])
  end

  def post_params
    params[:topic].require(:post).permit(:id, :topic_id, :name, :comment, :post_number, :owner_id, :picture)
  end

  def enough_authority
    unless logged_in_user?
      flash[:danger] = "ログインして下さい"
      redirect_to login_path
    end

    topic = Topic.find(params[:id])
    unless current_user&.all_posts_owner?(topic) || admin_user?
      flash[:danger] = "権限がありません"
      redirect_to root_path
    end
  end

  def basic_authentication
    authenticate_or_request_with_http_basic do |user, pass|
      (user == '@5JKTeamA' && pass == 'JoyfulRelay') || (user == '@5JKTeamB' && pass == 'JoyfulRelay')
    end
  end
end

app/views/topics/_form.html.slim
= markup do |m|
  - p = StaffFormPresenter.new(f, self)
  - m << p.notes
  - p.with_options(required: true) do |q|
    - m << q.text_field_block(:email, 'メールアドレス', size: 32)
    - m << q.password_field_block(:password, 'パスワード', size: 32)
    - m << q.full_name_block(:family_name,      :given_name,      '氏名')
    - m << q.full_name_block(:family_name_kana, :given_name_kana, 'フリガナ')
    - m << q.date_field_block(:start_date, '開始日')
    - m << q.date_field_block(:end_date,   '終了日', required: false)
  - m << p.suspended_box

app/views/topics/edit.html.slim
h1 スレッド名編輯

.form_design
  = form_with(model: @topic, local: true, class: 'ui form') do |f|
    == render 'shared/error_messages', object: f.object
    .field
      = f.label :title
      = f.text_field :title, autofocus: true
    = f.submit class: 'ui green button'

app/views/topics/index.html.slim
- provide(:title, 'スレッド一覧')

.ui.text.container
  h1 スレッド一覧
  table.ui.stackable.selectable.striped.table
    thead
      tr
        th.center.aligned  スレッド名
        th.center.aligned 投稿数
        th.center.aligned 最終投稿日
        - if admin_user?
          th
    tbody
      - TopicPresenter.build(@topics, self) do |topic|
          = topic.table_row
  br
  - if logged_in_user?
    => link_to "新スレッド作成", new_topic_path, class: 'ui small green button'

// pagination
== pagy_semantic_nav(@pagy)

app/views/topics/new.html.slim
h1 新スレッド作成

.topics
  = form_with model: @topic, html: { multipart: true }, class: 'ui form' do |f|
    == render "shared/error_messages", object: f.object

    .field
      = f.label :title
      = f.text_field :title, placeholder: "新スレッド名"

    = f.fields_for :post, html: { multipart: true } do |ff|
      = ff.hidden_field :topic_id
      .field
      = ff.label :comment, 'コメント'
      = ff.text_area :comment,
                     placeholder: "コメントをどうぞ＼(^_^)／"
      .custom-file
        = file_field_tag :upload_file, class: 'custom-file-input', accept: '*'
        label.custom-file-label.custom-file-label-kifu-or-image.text-left title=""
    = f.submit '作成する', class: 'ui small green button'

app/views/topics/show.html.slim
section.topics id="topic_#{@topic.id}"
  / タイトルやツールバーの表示
  = TopicPresenter.new(@topic, self).header

  div id="post_new_#{@topic.id}" class="hidden"
    / 新規投稿フォーム
    = form_with(model: [@topic, @topic.posts.build], html: { multipart: true }, local: true, class: 'ui form') do |f|
      == render "shared/error_messages", object: f.object
      - p = FormPresenter.new(f, self)
      = p.poster_block
      = p.comment_field_block
      = p.upload_file_block if logged_in_user?
      / 画像認証
      / = render 'shared/recaptcha' if guest_user?
      .field
        = p.submit_button
      br

  == render @posts

  // pagination
  == pagy_semantic_nav(@pagy)