config/routes.rb
Rails.application.routes.draw do
  get 'title_holders/index'
  get 'title_holders/show'
  get 'title_holders/new'
  get 'title_holders/edit'
  # サークル案内メニュー
  root 'welcome#index'

  resources :rating_distributions

  get 'circle_history'      => 'welcome#circle_history'
  get 'relay_shogi'         => 'welcome#relay_shogi'
  get 'circle_rule'         => 'welcome#circle_rule'
  get 'regular_meeting'     => 'welcome#regular_meeting'
  get 'faq'                 => 'welcome#faq'
  get 'faq_old'             => 'welcome#faq_old'
  get 'administration_rule' => 'welcome#administration_rule'
  get 'zainin_kikan'        => 'welcome#zainin_kikan'
  get 'join_us_information' => 'welcome#join_us_information'

  get 'usage'               => 'welcome#usage' # 利用方法

  # 会員名簿
  resources :users do
    resource :profile, only: [:new, :create, :show, :edit, :update]
  end
  # 順位
  resources :rankings

  # 研究会メニュー
  get 'laboratory'                      => 'laboratory#index'
  get 'laboratory/comment_kifu'         => 'laboratory#comment_kifu'
  get 'laboratory/gather'               => 'laboratory#gather'
  get 'laboratory/four_file_rook'       => 'laboratory#four_file_rook'
  get 'laboratory/right_king'           => 'laboratory#right_king'
  get 'laboratory/old_bbs'              => 'laboratory#old_bbs'
  get 'laboratory/particular_positions' => 'laboratory#particular_positions'
  get 'laboratory/migishiken'           => 'laboratory#migishiken'
  get 'laboratory/outline'              => 'laboratory#outline'

  resources :kifus do
    member do
      get 'json'
      get 'download'
      get 'downloads'
    end
  end

  # 棋戦メニュー
  get 'kisens/information'  => 'kisens#information'
  get 'kisens/common_rule' => 'kisens#common_rule'
  get 'kisens/handicap'    => 'kisens#handicap', as: :handicap
  resources :kisens do
    # resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
    # resource :card
  end
  resources :matchups do
    # resources :games, only: [:update]
  end
  # get 'game_dates'      => 'games#index'

  # 案内文
  resources :carousels
  resources :information, only: [:edit, :update]

  # 掲示板トップ
  get 'bbs' => 'bbs#index'
  resources :topics do
    resources :posts
  end

  # リンクメニュー
  resources :links, only: [:index, :new, :create, :update, :destroy]
  get   'links/edit'          => 'links#edit', as: :edit_links
  patch 'links/:link_id/sort' => 'links#sort', as: :link_sort

  # 会員登録・ログイン・ログアウトなど
  resources :sessions, only: [:new, :create, :destroy]
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # password resets
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 会員登録
  get  'sign_up'      => 'sign_up#new'
  post 'sign_up'      => 'sign_up#create'
  get  'registration' => 'registration#edit'
  post 'registration' => 'registration#update'

  # メールアドレスの確認
  get  'activation/:id' => 'registration#activation',     as: :activation

  # 入会承認/却下
  get 'approbation/:id' => 'account_approbation#approve', as: :approbation
  get 'rejection/:id'   => 'account_approbation#reject',  as: :rejection

  # 称号保持者
  resources :title_holders

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .ui.error.message
    i.close.icon
    .header
      = "#{object.errors.count} 箇所のエラーがあります。"
    ul.list
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_gravatar_edit.html.slim
.gravatar_edit
  => avatar_link_to @user, avatar_only: true
  = link_to 'アバター変更', "http://gravatar.com/emails", target: "_blank"

app/views/shared/_kifu.html.slim
- p = KifuPresenter.new(kifu, self)
- sente, gote = p.player1, p.player2

.shogi_container id="shogi_#{kifu.id}"
  / jkfe形式の棋譜データをDOMに埋め込む
  .hidden id="jkfe_#{kifu.id}" #{kifu.kifu}

  / 棋戦名など対局情報の表示
  .kifu_info
    = p.kifu_info

  / 相手（奥／左側）の駒台
  .komadai.komadai_1 id="komadai_1_#{kifu.id}"
    - 12.downto(1).each do |pos|
      = koma_tag(:blk, sprintf("k1%02d", pos))
  .mochigoma.mochigoma_1 id="mochigoma_1_#{kifu.id}" 0, 0, 0, 0, 0, 0, 0, 0
  .player_name_1 id="player_name_1_#{kifu.id}"
    p
      = "△#{gote}"

  / 将棋盤の用意
  = shogiban_tag(kifu.id, p.teai)

  / 自分（手前／右） の駒台
  .player_name_0 id="player_name_0_#{kifu.id}"
    p
      = "▲#{sente}"
  .komadai.komadai_0 id="komadai_0_#{kifu.id}"
    - 1.upto(12).each do |pos|
      = koma_tag(:blk, sprintf("k0%02d", pos))
  .mochigoma.mochigoma_0 id="mochigoma_0_#{kifu.id}" 0, 0, 0, 0, 0, 0, 0, 0

  / コメント枠
  .comment id="comment_#{kifu.id}"
    / kifu.comment
    / #=> { 0 => "対局前のコメント", 2 => "2手目へのコメント", 100 => "100手目へのコメント\r\nコメント" }
    / = form_with(model: Kifu.new, url: kifu_path("#{kifu.id}"), method: :patch) do |f|
    = form_with(model: Kifu.find(kifu.id), method: :patch) do |f|
      - (0..(p.moves.succ)).each do |n|
        - sh = (n == 0 ? "selected" : "hidden")
        = text_area_tag "#{n}", "#{kifu.comment[n]&.strip}", class: "msgbox #{n} #{sh}"

      - if logged_in_user?
        / 掲示板で複数の棋譜が表示されているとき、
        / どの棋譜へのコメント書き込みか識別するために、hidden_field_tagを使っている
        = hidden_field_tag :kifu_id, "#{kifu.id}", id: "kifu_id_0"
        = f.submit 'ｺﾒﾝﾄ書込', class: "ui basic brown button write_comment"

        / 生棋譜データ(kif形式) download
        = KifuPresenter.new(kifu, self).kifu_download_button

  / 棋譜コントロールパネル
  .panel data-kifu-number="#{kifu.id}"
    / 棋譜リストを生成
    .list.selectbox[id="kifu_list_#{kifu.id}" data-kifu-number="#{kifu.id}" data-kifu-max="#{kifu.kifu.length}"]
      a.select[href="#" data-kifu-number="#{kifu.id}"]
        span --開始局面--
      .pulldown.hidden
        - asterisk = kifu.comment[0].present? ? '* ' : '&nbsp;&nbsp;'.html_safe
        a.selected href='0'
          | #{asterisk} --開始局面--

        - kifu.kifu.each_with_index do |kif, n|
          - next if n == 0
          - asterisk = kifu.comment[n].present? ? '* ' : '&nbsp;&nbsp;'
          = link_to "#{asterisk} #{n}. #{code2te(kif)}".html_safe, n.to_s
        / TODO: 投了でない場合もあるけれど
        = link_to "&nbsp;&nbsp;&nbsp;#{p.moves+1}. #{p.loser_mark}投了".html_safe, (p.moves).to_s

      / 現在、何手目を表示しているのか
      input.current_te type="hidden" value="0" id="current_te_#{kifu.id}"


  / 棋譜プレーヤー
  .kifu_player
    / 棋譜再生速度を生成
    .speed.selectbox id="kifu_speed_#{kifu.id}"  data-kifu-number="#{kifu.id}"
      a.select href="#"
        span 普通
      .pulldown.hidden
        a href="s250" 超速
        a href="s500" 速い
        a.selected href="s1000" 普通
        a href="s1750" 遅い
        a href="s2500" 激遅
      input.kifu_speed type="hidden" value="s1000" id="current_speed_#{kifu.id}" data-kifu-number="#{kifu.id}"
    input.kifu_first  type="button" id="kifu_first_#{kifu.id}"  value="|<" disabled="true" data-kifu-number="#{kifu.id}"
    input.kifu_prev   type="button" id="kifu_prev_#{kifu.id}"   value=" <" disabled="true" data-kifu-number="#{kifu.id}"
    input.kifu_play   type="button" id="kifu_play_#{kifu.id}"   value="▶" data-kifu-number="#{kifu.id}" data-kifu-max="#{kifu.kifu.length}"
    input.kifu_next   type="button" id="kifu_next_#{kifu.id}"   value=" >" data-kifu-number="#{kifu.id}"
    input.kifu_last   type="button" id="kifu_last_#{kifu.id}"   value=">|" data-kifu-number="#{kifu.id}" data-kifu-max="#{kifu.kifu.length}"
    input.kifu_invert type="button" id="kifu_invert_#{kifu.id}" value="反転" data-kifu-number="#{kifu.id}"

app/views/shared/_kifu_modal.html.slim
.shogi_container[id="shogi_0"]
  / jkfe形式の棋譜データをDOMに埋め込む
  .hidden#jkfe_0
  / 棋戦名などの表示
  .kifu_info
    / Ajax で直接書き込み
    / p  == render partial: "shared/kifu_info", locals: { info: kifu.info }

  / 相手（奥／左側）の駒台
  .komadai.komadai_1[id="komadai_1_0"]
    - 12.downto(1).each do |pos|
      = koma_tag(:blk, "k1#{'%02d' % pos}")
  .mochigoma[id="mochigoma_1_0"] 0, 0, 0, 0, 0, 0, 0, 0
  .player_name_1[id="player_name_1_0"]

  / 将棋盤
  / 駒落ちの場合も、Ajaxで修正済み
  = shogiban_tag(0, "平手")

  / 自分（手前／右） の駒台
  .player_name_0[id="player_name_0_0"]
  .komadai.komadai_0[id="komadai_0_0"]
  - (1..12).each do |pos|
    = koma_tag(:blk, "k0#{'%02d' % pos}")
    .mochigoma[id="mochigoma_0_0"] 0, 0, 0, 0, 0, 0, 0, 0

  / コメント枠
  .comment[id="comment_0"]
    / #=> { 0 => "対局前のコメント", 2 => "2手目へのコメント", 100 => "100手目へのコメント\r\nコメント" }
    = form_for(:kifu, url: kifu_path(28), method: :patch) do |f|
      - (0...300).each do |n|
        - sh = n == 0 ? "selected" : "hidden"
        = text_area_tag "#{n}", "", class: "msgbox #{n} #{sh}"
      - if logged_in_user?
        = hidden_field_tag :kifu_id_for_comment, ""
        = f.submit 'ｺﾒﾝﾄ書込', class: "btn btn-sm btn-light write_comment"

  / 棋譜コントロールパネル
  .panel data-kifu-number="0"
    / 棋譜リストを生成
    .list.selectbox[id="kifu_list_0" data-kifu-number="0" data-kifu-max="0"]
      a.select[href="#" data-kifu-number="0"]
        span --開始局面--
      .pulldown.hidden
        = link_to "--開始局面--", "0"
        - (1..300).each do |n|
          = link_to "#{n}. ▲２六歩", n.to_s
        / # 実際の差し手は Ajax で書き換え

      / 現在、何手目を表示しているのか
      input.current_te[type="hidden" value="0" id="current_te_0"]

    / 棋譜再生速度
    .speed.selectbox[id="kifu_speed_0"  data-kifu-number="0"]
      a.select[href="#"]
        span 普通
      .pulldown.hidden
        a[href="s250"] 超速
        a[href="s500"] 速い
        a.selected[href="s1000"] 普通
        a[href="s1750"] 遅い
        a[href="s2500"] 激遅
      input.kifu_speed[type="hidden" value="s1000" id="current_speed_0" data-kifu-number="0"]

    / 棋譜プレーヤー
    .kifu_player
      input.kifu_first [type="button" id="kifu_first_0"  value="|<" disabled="true" data-kifu-number="0"]
      input.kifu_prev  [type="button" id="kifu_prev_0"   value=" <" disabled="true" data-kifu-number="0"]
      input.kifu_play  [type="button" id="kifu_play_0"   value="▶"   data-kifu-number="0" data-kifu-max="0"]
      input.kifu_next  [type="button" id="kifu_next_0"   value=" >"   data-kifu-number="0"]
      input.kifu_last  [type="button" id="kifu_last_0"   value=">|"   data-kifu-number="0" data-kifu-max="0"]
      input.kifu_invert[type="button" id="kifu_invert_0" value="反転" data-kifu-number="0"]

  / 生棋譜データ(kif形式, ki2形式) download
  - if logged_in_user?
    = form_for(:kifu, url: download_kifu_path(0), method: :get) do |f|
      = hidden_field_tag :kifu_id_for_download, ""
      = f.submit '棋譜保存', class: "btn btn-sm btn-light download_kifu"

  / button.btn.btn-default.btn-sm.show_kifu[data-toggle="collapse" data-target="#raw_kifu_0"]
  /   | kif形式
  / div[id="raw_kifu_0" class="collapse out"]
  /   textarea.raw_kifu

app/views/shared/_recaptcha.html.slim
.recaptcha
  script src="https://www.google.com/recaptcha/api/challenge?k=6Lc9bREUAAAAAM-bT6gY24FQbLWXgrfap-llLzbQ"
  = get_captcha(options: { theme: 'white' }).html_safe

app/views/shared/_search_form.html.slim
/ TODO: 検索が利かない

.well.collapse.search_form
  = search_form_for(@q, url: yield(:search_path)) do |f|
    - name_cont    = "name_cont"
    - comment_cont = "comment_cont"
    - if yield(:search_path) == root_path
      - name_cont    = "posts_name_cont"
      - comment_cont = "posts_comment_cont"
      .form-inline
        = f.label      :title_cont, 'スレッド名'
        = f.text_field :title_cont, class: 'form-control'
      br

    .form-inline
      = f.label      name_cont, '投稿者'
      = f.text_field name_cont, class: 'form-control'
    br
    .form-inline
      = f.label      comment_cont, 'コメント'
      = f.text_field comment_cont, class: 'form-control'
    br
    .form-inline
      = f.label :updated_at_gteq, '更新日'
      = f.date_field :updated_at_gteq, class: 'form-control datepicker text-center', name: 'start'
      | 〜
      = f.date_field :updated_at_lteq, class: 'form-control datepicker text-center', name: 'end'
    br
    = f.submit '検索', class: 'btn btn-success'