config/routes.rb
Rails.application.routes.draw do
  get 'title_holders/index'
  get 'title_holders/show'
  get 'title_holders/new'
  get 'title_holders/edit'
  # サークル案内メニュー
  root 'welcome#index'

  resources :rating_distributions

  get 'circle_history'      => 'welcome#circle_history'
  get 'relay_shogi'         => 'welcome#relay_shogi'
  get 'circle_rule'         => 'welcome#circle_rule'
  get 'regular_meeting'     => 'welcome#regular_meeting'
  get 'faq'                 => 'welcome#faq'
  get 'faq_old'             => 'welcome#faq_old'
  get 'administration_rule' => 'welcome#administration_rule'
  get 'zainin_kikan'        => 'welcome#zainin_kikan'
  get 'join_us_information' => 'welcome#join_us_information'

  get 'usage'               => 'welcome#usage' # 利用方法

  # 会員名簿
  resources :users do
    resource :profile, only: [:new, :create, :show, :edit, :update]
  end
  # 順位
  resources :rankings

  # 研究会メニュー
  get 'laboratory'                      => 'laboratory#index'
  get 'laboratory/comment_kifu'         => 'laboratory#comment_kifu'
  get 'laboratory/gather'               => 'laboratory#gather'
  get 'laboratory/four_file_rook'       => 'laboratory#four_file_rook'
  get 'laboratory/right_king'           => 'laboratory#right_king'
  get 'laboratory/old_bbs'              => 'laboratory#old_bbs'
  get 'laboratory/particular_positions' => 'laboratory#particular_positions'
  get 'laboratory/migishiken'           => 'laboratory#migishiken'
  get 'laboratory/outline'              => 'laboratory#outline'

  resources :kifus do
    member do
      get 'json'
      get 'download'
      get 'downloads'
    end
  end

  # 棋戦メニュー
  get 'kisens/information'  => 'kisens#information'
  get 'kisens/common_rule' => 'kisens#common_rule'
  get 'kisens/handicap'    => 'kisens#handicap', as: :handicap
  resources :kisens do
    # resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
    # resource :card
  end
  resources :matchups do
    # resources :games, only: [:update]
  end
  # get 'game_dates'      => 'games#index'

  # 案内文
  resources :carousels
  resources :information, only: [:edit, :update]

  # 掲示板トップ
  get 'bbs' => 'bbs#index'
  resources :topics do
    resources :posts
  end

  # リンクメニュー
  resources :links, only: [:index, :new, :create, :update, :destroy]
  get   'links/edit'          => 'links#edit', as: :edit_links
  patch 'links/:link_id/sort' => 'links#sort', as: :link_sort

  # 会員登録・ログイン・ログアウトなど
  resources :sessions, only: [:new, :create, :destroy]
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # password resets
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 会員登録
  get  'sign_up'      => 'sign_up#new'
  post 'sign_up'      => 'sign_up#create'
  get  'registration' => 'registration#edit'
  post 'registration' => 'registration#update'

  # メールアドレスの確認
  get  'activation/:id' => 'registration#activation',     as: :activation

  # 入会承認/却下
  get 'approbation/:id' => 'account_approbation#approve', as: :approbation
  get 'rejection/:id'   => 'account_approbation#reject',  as: :rejection

  # 称号保持者
  resources :title_holders

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # トップページ
  def index
    # 最終更新日
    @last_update      = Message.maximum(:updated_at)
    # 告知
    @carousel         = Carousel.first
    # 名局紹介
    @well_played_game = Kifu.first
    # タイトル保持者
    @title_holders    = TitleHolder.current
  end

  # 5JKの歴史
  def circle_history
  end

  # 24リレー成績
  def relay_shogi
  end

  # サークル案内(会則)
  def circle_rule
  end

  # サークル案内(旧会則)
  def circle_rule_old
  end

  # 例会案内
  def regular_meeting
  end

  # よくある質問
  def faq
  end

  # 運営規則
  def administration_rule
  end

  # 旧運営規則
  def administration_rule_old
  end

  # 役員在任期間
  def zainin_kikan
  end

  # # 会員登録 ご案内
  def join_us_information
  end

  # 利用方法
  def usage
    render layout: 'application'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def topic_title_post_count(topic, classname = '')
    if topic.updated_at >= Time.current.days_ago(7)
      link_to("#{topic.title}(#{topic.posts.count})#{image_tag('new-1.gif')}  ".html_safe, topic_path(topic), class: classname)
    else
      link_to "#{topic.title}(#{topic.posts.count}) ", topic, class: classname
    end
  end
end

app/views/welcome/_officers_list.html.slim
table.table.table-hover
  tbody
    tr
      th
        | 役職
      th
        | ＨＮ（現職者）
      th
        | 主　任
      th
        | 備　考
    tr
      th
        | 会　長
      td
        | z-air-6
      td
        | 運営役員人事／運営方針の決定／各主任への助言・補助／会員課他
      td
        | H29.04.18会長交代
    tr
      th
        | 副会長
      td
        | WhiteWizard
      td
        | ＨＰ主任／棋戦主任
      td
        | H23.06.01修正
    / tr
    /   th
    /     | 幹　事
    /   td
    /     | kouki3110
    /   td
    /     | ＨＰ副主任（募集要項、棋譜担当）
    /   td
    /     | H21/12/01修正
    / tr
    /   th
    /     | 幹　事
    /   td
    /     | warabi.t
    /   td
    /     | ＨＰ副主任（対戦表担当）
    /   td
    /     | H21/12/01修正
    tr
      th
        | 幹　事
      td
        | MAT_FIBER
      td
        | 例会主任／棋戦副主任（対戦表作成）
      td
        | H23.06.01修正
    / tr
    /   th
    /     | 幹　事
    /   td
    /     | t-minato
    /   td
    /     | 例会副主任
    /   td
    /     | H22/06/23修正
    / tr
    /   th
    /     | 幹　事
    /   td
    /     | z-air-6
    /   td
    /     | ＨＰ副主任（会員課）
    /   td
    /     | H23/06/01修正
    tr
      th
        | 幹　事
      td
        | iochigen
      td
        | 棋戦副主任（対戦表作成）
      td
        | H24.03.24修正
    tr
      th
        | 幹　事
      td
        | thegul
      td
        |
      td
        | H29.04.01修正
    tr
      th
        | 相談役
      td
        | horidashido
      td
        | 運営への助言
      td
        | H23.06.01修正
    tr
      th
        | 相談役
      td
        | akatuka
      td
        | 運営への助言
      td
        | H23.06.01修正

app/views/welcome/circle_rule.html.slim
- provide(:title, '会則')

.ui.segments
  .ui.segment
    h1.ui.center.aligned.header
        small
          | ８１道場で&nbsp;
        | 五級位上昇を目指す会
        br
        | ご案内
    .ui.teal.segment
      h2
        | １．目標
      p
        ul
          li
            | ８１道場で五級位の上昇を目指す。
          li
            | 特に、下級者の方の棋力の向上を目指す。
      p.ml-1
        | 例えば、12級の方は7級を、5級の方は初段をと、現在の級位の五つ上を目指して活動するサークルです。
        br
        | 有段者の方は五つ上の段位にとらわれず、各自の高みを目指し研鑽を積むとともに、後進の指導にあたっていただければと思います。

    .ui.teal.segment
      h2
        | ２．本会の活動
      p
        |  ８１道場を利用して、本会独自の棋戦・研究会を行う。
        br
        |  その際、感想戦に重点を置く。

    .ui.teal.segment
      h2
        | ３．会員資格
      ol.lower-latin
        li
          | ８１道場で級位（段位）の上昇・向上を目指していること。
        li
          | 日常から、感想戦をすることを心がけていること。
        li
          | 志の保てる人。過少申告や点数調整は絶対にしない方。

    .ui.teal.segment
      h2
        | ４．会員のなすべきこと
      ol
        li
          | 五級位上昇を目指して切磋琢磨する。
        li
          | 「五級位上昇を目指す会」の棋戦にできるだけ参加する。
        li
          | 棋戦では、必ず
          strong
            u
              | 感想戦をしっかりやる。
        li
          | 例会にできるだけ参加する。例会は毎週土曜２１時からです。詳しくは
          = link_to 'こちら', regular_meeting_path
        li
          | Webサイトを持っている方は、（できれば）五級位上昇を目指す会トップページ&nbsp;
          => link_to 'https://shogi-5jk.herokuapp.com', root_path
          | へのリンクを貼る。(バナー画像はトップページにあります)
        li
          | メンバー同士での稽古将棋もどんどんやること。
          | 掲示板を活用して約束したりして下さい。
        li
          | 研究会などは、自由に呼びかけて開催して下さい。
        li
          | 自戦記を掲示板に簡潔に載せるのもいい方法だと思います。会員のみんなに棋譜を見てもらって、コメントを求めましょう。
          p
            small
              |  注意：5JKで行われる棋戦及び研究会などの棋譜は、5JKのWebサイトなどで公開となります。あらかじめご了承下さい。会員の棋力向上に役立てるのが目的です。

    .ui.teal.segment
      h2
        | ５．禁止事項
      p
        |  以下の事項の一つ及び複数に該当した場合には、会員資格を停止、若しくは喪失します。
      ol
        li
          | 著しくマナーに反する行為が確認されたとき
          br
          |  (ソフトの使用、Ｒ点の任意の調整、Ｒ点の過少申告による棋戦の参加等)
        li
          | 不正行為が確認されたとき
        li
          | 相手を誹謗中傷したり暴言を吐いたりしたことが確認されたとき
        li
          | 長期間理由なくサークル活動に参加されなかったとき
        li
          | その他会員として不適格と判断した場合

    .ui.teal.segment
      h2
        | ６．会員登録
      article
        p
          span.ui.green.text
            | 以上にご賛同いただける方は、入会申込なさってください。
          br
          |  「入会を申し込む」をクリックすると、入会登録のフォーム画面になります。

        .ui.center.aligned.header
          => link_to '入会を申し込みません', root_path, class: 'ui red basic button'
          => link_to '入会を申し込みます', sign_up_url, class: 'ui green button'
      p
        | もし、正常に送信・登録できない場合は、
        br
        |  必要事項 (登録ハンドルネーム / 現在の段級位 / 現在のレーティング / メールアドレス / お好きな棋士 / 入会の抱負)
        br
        |  をご記入の上、
        b => link_to 'メール', mail_to_5JK_url
        | を送ってください。

app/views/welcome/circle_rule_old.html.slim
- provide(:title, '会則')

scss:
  //colors
  $color_cinnabar_approx: #e44444;
  $white: #fff;
  $color_broom_approx: #f7f716;
  $color_persian_blue_approx: #2e35f1;
  $color_sweet_pink_approx: #f6a3a3;
  $color_malachite_approx: #1bef3b;
  $color_harlequin_approx: #48ee0c;
  $color_chardonnay_approx: #f7c582;
  $black:  black;
  $color_oyster_bay_approx: #d9ffff;
  $color_loafer_approx: #f1f2e0;
  $color_fair_pink_approx: #ffeaea;
  $color_night_rider_approx: #1a1515;
  $color_red_approx: rgba(240,0,0,1);
  $color_forest_green_approx: #218c31;
  $color_evening_sea_approx: #005a42;
  $color_falu_red_approx: #842117;
  $color_bay_of_many_approx: #17428c;
  $red: #ff0000;
  $color_catalina_blue_approx: rgba(16,33,116,1);
  $color_salem_approx: #008439;
  $color_windsor_approx: rgba(62,15,123,1);
  $color_monza_approx: #e20915;
  $color_tory_blue_approx: #0f529c;
  $color_apple_approx: #389c41;
  $color_bitter_lemon_approx: #d7d902;
  $color_mine_shaft_approx: #333333;
  $color_dodger_blue_approx: #0f94f7;
  $color_bunting_approx: rgba(25,17,75,1);
  $color_vivid_violet_approx: #8e28a0;
  $color_flamingo_approx: #e65920;
  $color_bright_turquoise_approx: #00c9ff;
  $color_siren_approx: #8d003a;
  $color_torea_bay_approx: #173194;
  $color_mariner_approx: #1e72d0;
  $color_rock_approx: rgba(81,49,48,1);
  $color_astronaut_approx: #243a6a;
  $color_san_marino_approx: #4a73b5;
  $color_korma_approx: #99470e;
  $color_punga_approx: #4a3910;
  $color_heath_approx: #5a0f17;
  $color_dark_burgundy_approx: rgba(116,17,15,1);
  $color_gorse_approx: #fcf74b;
  $color_te_papa_green_approx: #215231;
  $color_guardsman_red_approx: #bd0000;
  $color_endeavour_approx: #0063ad;
  $color_viridian_approx: #448770;
  $color_azure_radiance_approx: #0793ff;
  $color_crown_of_thorns_approx: rgba(116,34,34, 1);
  $color_starship_approx: #efe742;
  $color_lochmara_60_approx: rgba(0,121,186,0.6);
  $blue: blue;
  $color_malibu_approx: #7fc0fc;
  $color_watusi_approx: #ffdfd0;
  $color_blue_chalk_approx: #ebd7ff;
  $color_sweet_corn_approx: #f9f08c;
  $color_royal_purple_approx: rebeccapurple;

  table {
    &#map {
      font-size: 10pt;
      text-align: left;
      border: 1px double $black;
      background: $color_oyster_bay_approx;
      // height: 540px;
      // width: 720px;
      color: $color_loafer_approx;
      border-collapse: collapse;
      margin: 0 auto;
      td {
        text-align: center;
        border: 2px solid $color_oyster_bay_approx;
        span.member {
          color: $color_fair_pink_approx;
        }
      }
    }
    td.note {
      text-align: left !important;
      color: $color_night_rider_approx;
    }
  }
  .hokkaido {
    background: $color_red_approx;
  }
  .aomori {
    background: $color_forest_green_approx;
  }
  .iwate {
    background: $color_evening_sea_approx;
  }
  .miyagi {
    background: $color_forest_green_approx;
  }
  .akita {
    background: $color_falu_red_approx;
  }
  .yamagata {
    background: $color_bay_of_many_approx;
  }
  .fukushima {
    background: $red;
  }
  .ibaragi {
    background: $color_catalina_blue_approx;
  }
  .tochigi {
    background: $color_salem_approx;
  }
  .gunma {
    background: $color_windsor_approx;
  }
  .saitama {
    background: $color_monza_approx;
  }
  .chiba {
    background: $color_tory_blue_approx;
  }
  .tokyo {
    background: $color_apple_approx;
  }
  .kanagawa {
    background: $red;
  }
  .niigata {
    background: $color_bitter_lemon_approx;
    color: $color_night_rider_approx;
    span.member {
      color: $color_mine_shaft_approx !important;
    }
  }
  .toyama {
    background: $color_forest_green_approx;
  }
  .ishikawa {
    background: $color_dodger_blue_approx;
  }
  .fukui {
    background: $color_bunting_approx;
  }
  .yamanashi {
    background: $color_vivid_violet_approx;
  }
  .nagano {
    background: $color_flamingo_approx;
  }
  .gifu {
    background: $color_forest_green_approx;
  }
  .shizuoka {
    background: $color_flamingo_approx;
  }
  .aichi {
    background: $color_falu_red_approx;
  }
  .mie {
    background: $color_apple_approx;
  }
  .shiga {
    background: $color_bright_turquoise_approx;
  }
  .kyoto {
    background: $color_siren_approx;
  }
  .osaka {
    background: $color_torea_bay_approx;
  }
  .hyogo {
    background: $color_mariner_approx;
  }
  .nara {
    background: $color_rock_approx;
  }
  .wakayama {
    background: $color_astronaut_approx;
  }
  .tottori {
    background: $color_san_marino_approx;
  }
  .shimane {
    background: $color_korma_approx;
  }
  .okayama {
    background: $color_punga_approx;
  }
  .hiroshima {
    background: $color_heath_approx;
  }
  .yamaguchi {
    background: $color_dark_burgundy_approx;
  }
  .tokushima {
    background: $color_gorse_approx;
    color: $color_night_rider_approx;
    span.member {
      color: $color_mine_shaft_approx !important;
    }
  }
  .kagawa {
    background: $color_te_papa_green_approx;
  }
  .ehime {
    background: $color_gorse_approx;
    color: $color_night_rider_approx;
    span.member {
      color: $color_mine_shaft_approx !important;
    }
  }
  .kochi {
    background: $color_guardsman_red_approx;
  }
  .fukuoka {
    background: $color_endeavour_approx;
  }
  .saga {
    background: $color_viridian_approx;
  }
  .nagasaki {
    background: $color_azure_radiance_approx;
  }
  .kumamoto {
    background: $color_crown_of_thorns_approx;
  }
  .oita {
    background: $color_red_approx;
  }
  .miyazaki {
    background: $color_starship_approx;
    color: $color_night_rider_approx;
    span.member {
      color: $color_mine_shaft_approx !important;
    }
  }
  .kagoshima {
    background: $color_red_approx;
  }
  .okinawa {
    background: $color_red_approx;
  }
  .overseas {
    background: $color_lochmara_60_approx;
  }
  #update {
    color: $red;
    text-align: center;
    padding-bottom: 10pt;
  }
  .map {
    background: $color_oyster_bay_approx;
    border: 5px groove $color_malibu_approx;
  }

  h1 {
    text-shadow: 0 -1px 1px $color_cinnabar_approx, -1px 0 1px $white, 1px 0 1px $white, 0 1px 1px $color_broom_approx, 3px 1px 1px $color_persian_blue_approx, 2px 2px 2px $color_sweet_pink_approx, 3px 3px 3px $color_malachite_approx;
    color: $color_harlequin_approx;
  }

.card.p-4.mb-4
  .card-body
    h1.text-center.mb-4
        | 将棋クラブ24で
        br
        | 五級位上昇を目指す会について

  section.card-body.mt-3.mb-3.map
    = render 'map'
  section.card-body.mt-3.mb-3.rounded.border.border-primary
      h3
        | １．目標
      ul
        li
          | 将棋倶楽部２４で５級位（５段位）の上昇をめざす。
        li
          | 特に、下級者（10級前後）の方の棋力の向上を目指す。
      article[style="margin-left: 50px;"]
        p
          small
            |  例えば、現在１２級の方は５級上の７級を目指し、達成できればめでたく本会の卒業です。
            br
            |  また、別な例では４級の方が５級位上の二段になれば卒業です。
            br
            |  卒業しても、本人が希望すれば新しい目標で再入会することができます。
  section.card-body.mt-3.mb-3.rounded.border.border-primary
    h3
      | ２．会員資格
    ol[style="list-style-type:lower-latin"]
      li
        | 将棋倶楽部２４で級位（段位）の上昇・向上を目指していること。
      li
        | 次のいづれかを満たしていること。
        ol[style="list-style-type:decimal"]
          li
            | 将棋倶楽部２４で７級以下の場合（Ｒ950未満＝本会員）
          li
            | 将棋倶楽部２４で６級以上の方は、駒落ち棋戦等で指導対局していただける方に限ります（＝上級会員）
          li
            | 将棋倶楽部２４で初段〜三段の方は、卒業要件の段位を自己申告して頂きます。
            br
            |  （例：二段→五段、三段→四段など）　つまり入会時、段位の方は五段位上昇にこだわりません。
            br
            |  その他の入会要件は、ｂ．-2.項と同じです。
          li
            | 四段以上の高段位の方は本人が希望すれば、卒業要件を設けずに５ＪＫで活動することができます。
            br
            |  ただし、他の会員の棋力向上のために指導していただける方に限ります。
      li
        | 対局数が100局以上であること
      li
        | 日常から、感想戦をすることを心がけていること
      li
        | 志の保てる人。過少申告や点数調整は絶対にしない
      li
        | 入会時に、有効なメールアドレスを登録できない人は、入会を承認できません。
  section.card-body.mt-3.mb-3.rounded.border.border-primary
    h3
      | ３．会員のなすべきこと
    ol[style="list-style-type:lower-latin"]
      li
        | 五級位上昇を目指して切磋琢磨する。
      li
        | 「五級位上昇を目指す会」の棋戦にできるだけ参加する。
      li
        | 棋戦では、必ず
        strong
          u
            | 感想戦をしっかりやる
      li
        | 例会にできるだけ参加する。例会は毎週土曜２１時からです。詳しくは
        = link_to 'こちら', regular_meeting_path
      li
        | Webサイトを持っている方は、五級位上昇を目指す会トップページ
        = link_to 'https://shogi-5jk.herokuapp.com', root_path
        | へのリンクを貼る。（できれば）
        br
        |  （バナー画像はトップページにあります）
      li
        | 五級位上昇が達成できたら（入会時の級位から）「卒業」です。以後は本人の希望があれば、さらに上の五級位上昇を目指して再入会できます。（任意）
      li
        | もちろん、メンバー同士でのスパーリング（稽古将棋）もどんどんやること。
        | 掲示板を活用して約束したりして下さい。
      li
        | 研究会などは、自由に呼びかけて開催して下さい。
      li
        | 自戦記を掲示板に簡潔に載せるのもいい方法だと思います。会員のみんなに棋譜を見てもらって、コメントを求めましょう。
        p
          small
            |  注意：5JKで行われる棋戦及び研究会などの棋譜は、5JKのWebサイトで公開となります。あらかじめご了承下さい。会員の棋力向上に役立てるのが目的です。

  section.card-body.mt-3.mb-3.rounded.border.border-primary
    h3
      | ４．登録方法
    p
      / => link_to 'こちら', member_registration_path
      => link_to 'こちら', join_us_information_path
      | から登録して下さい。

  section.card-body.mt-3.mb-3.rounded.border.border-primary
    h3
      | ５．禁止事項
    p
      |  以下の事項の一つ及び複数に該当した場合には、会員資格の停止及び喪失する
    ol
      li
        | 著しくマナーに反する行為が確認されたとき
        br
        |  (ソフトの使用、Ｒ点の任意の調整、Ｒ点の過少申告による棋戦の参加等)
      li
        | 不正行為が確認されたとき
      li
        | 相手を誹謗中傷したり暴言を吐いたりしたことが確認されたとき
      li
        | 長期間理由なくサークル活動に参加されなかったとき
      li
        | 一定期間、登録したメールアドレスに連絡が付かない場合、または有効な新しいメールアドレスを再登録できない人は、退会処理をします。
      li
        | その他会員として不適格と判断した場合

  section.card-body.mt-3.mb-3.rounded.border.border-primary
    h3
      | ６．本会の活動
    p
      |  倶楽部２４を利用して、本会独自の棋戦・研究会を行う。
      br
      |  その際、感想戦に重点を置く。

app/views/welcome/join_us_information.html.slim
.card.p-4.mb-4
  .card-body.m-2.mb-4.p-3
    h1.text-success.text-center
      small 将棋倶楽部24で
      br
      | 五級位上昇を目指す会
      br
      small 〜 会員登録 ご案内 〜

  section.card-body.rounded.border.border-primary.m-2.mb-4.p-3
    h3 会員資格
    ol style="list-style-type:lower-latin"
      li
        | 将棋倶楽部２４で級位（段位）の上昇・向上を目指していること。
      li
        | 次のいずれかを満たしていること。
        ol
          li
            | 将棋倶楽部２４で７級以下の場合（Ｒ950未満＝本会員）
          li
            | 将棋倶楽部２４で６級以上の方は、駒落ち棋戦等で指導対局していただける方に限ります（＝上級会員）。
          li
            | 将棋倶楽部２４で初段〜三段の方は、卒業要件の段位を自己申告して頂きます（例：二段→五段、三段→四段など）。
            br
            |  つまり入会時、段位の方は五段位上昇にこだわりません。その他の入会要件は、前項と同じです。
          li
            | 四段以上の高段位の方は本人が希望すれば、卒業要件を設けずに５ＪＫで活動することができます。
            br
            |  ただし、他の会員の棋力向上のために指導していただける方に限ります。
      li
        | Ｒ戦の対局数が100局以上であること。
        br
        span[style="font-size:small"]
          span[style="color:red"]
            | （レーティング戦100局未満の方の入会は全てお断りしています。
          | 100局以上になったら再度、登録願えますか）
      li
        | 日常から、感想戦をすることを心がけていること。
      li
        | 志の保てる人。過少申告や点数調整は絶対にしない。
      li
        | ６棋戦連続、棋戦不参加の方は「活動中会員名簿」から「休止中会員名簿」へ移行します。
        br
        |  （休止中会員でも棋戦参加できます。また棋戦参加時点で「活動中会員」へ移行します。）
      li
        | 入会時に、有効なメールアドレスを登録できない人は、入会を承認できません。
    article.ml-5
      p.small
        |  注意：5JKで行われる棋戦及び研究会などの棋譜は、5JKのWebサイトで公開となります。あらかじめご了承下さい。
        br
        |  会員の棋力向上に役立てるのが目的です。
        br
        |  ※場合によっては入会をお断りすることがあります。
        br
        |  例：入会登録時に故意の反則がないかどうかなどの棋譜チェックをさせていただきます。
        br
        |  その際、棋譜検索で検出される棋譜の数が少ない場合は、仮入会をお願いすることもあります。（H.21/10/11追記）

  section.card-body.rounded.border.border-primary.m-2.mb-4.p-3
    h3 登録前のお願い
    p.text-success.lead
      |  会員登録の前に、以下のルールを確認してください。

    article
      p
        |  以下の事項の一つ及び複数に該当した場合には、会員資格の停止及び喪失する。
      ol
        li
          | 著しくマナーに反する行為が確認されたとき
          br
          |  (ソフトの使用・R点の任意の調整 / R点の過少申告による棋戦の参加等)
        li
          | 不正行為が確認されたとき。
        li
          | 相手を誹謗中傷したり暴言を吐いたりしたことが確認されたとき。
        li
          | 五級位上昇を目指す会の信用を傷つけたとき。
        li
          | 長期間理由なくサークル活動に参加されなかったとき。
        li
          | 一定期間、登録したメールアドレスに連絡が付かない場合、または有効な新しいメールアドレスを再登録できない人は、退会処理をします。
        li
          | その他会員として不適格と判断した場合。

  section.card-body.rounded.border.border-primary.m-2.mb-4.p-3
    h3 会員登録
    article
      p
        span.text-success.lead
          | 以上の７つの事項を行わないと承諾しますか？
        br
        |  どちらかをクリックしてください。
        br
        |  「承諾します」をクリックすると、入会登録のフォーム画面になります。

      .text-center
        => link_to '承諾しません', root_path, class: 'btn btn-md btn-outline-danger'
        => link_to '承諾します', sign_up_url, class: 'btn btn-md btn-primary'
    p
      | もし、正常に送信・登録できない場合は、
      br
      |  必要事項 (登録ハンドルネーム / 現在の段級位 / 現在のR / メールアドレス / お好きな棋士 / 在住都道府県 / 入会の抱負)
      br
      |  をご記入の上、
      b => link_to 'メール', mail_to_5JK_url
      | を送ってください。