config/routes.rb
Rails.application.routes.draw do
  get 'title_holders/index'
  get 'title_holders/show'
  get 'title_holders/new'
  get 'title_holders/edit'
  # サークル案内メニュー
  root 'welcome#index'

  resources :rating_distributions

  get 'circle_history'      => 'welcome#circle_history'
  get 'relay_shogi'         => 'welcome#relay_shogi'
  get 'circle_rule'         => 'welcome#circle_rule'
  get 'regular_meeting'     => 'welcome#regular_meeting'
  get 'faq'                 => 'welcome#faq'
  get 'faq_old'             => 'welcome#faq_old'
  get 'administration_rule' => 'welcome#administration_rule'
  get 'zainin_kikan'        => 'welcome#zainin_kikan'
  get 'join_us_information' => 'welcome#join_us_information'

  get 'usage'               => 'welcome#usage' # 利用方法

  # 会員名簿
  resources :users do
    resource :profile, only: [:new, :create, :show, :edit, :update]
  end
  # 順位
  resources :rankings

  # 研究会メニュー
  get 'laboratory'                      => 'laboratory#index'
  get 'laboratory/comment_kifu'         => 'laboratory#comment_kifu'
  get 'laboratory/gather'               => 'laboratory#gather'
  get 'laboratory/four_file_rook'       => 'laboratory#four_file_rook'
  get 'laboratory/right_king'           => 'laboratory#right_king'
  get 'laboratory/old_bbs'              => 'laboratory#old_bbs'
  get 'laboratory/particular_positions' => 'laboratory#particular_positions'
  get 'laboratory/migishiken'           => 'laboratory#migishiken'
  get 'laboratory/outline'              => 'laboratory#outline'

  resources :kifus do
    member do
      get 'json'
      get 'download'
      get 'downloads'
    end
  end

  # 棋戦メニュー
  get 'kisens/information'  => 'kisens#information'
  get 'kisens/common_rule' => 'kisens#common_rule'
  get 'kisens/handicap'    => 'kisens#handicap', as: :handicap
  resources :kisens do
    # resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
    # resource :card
  end
  resources :matchups do
    # resources :games, only: [:update]
  end
  # get 'game_dates'      => 'games#index'

  # 案内文
  resources :carousels
  resources :information, only: [:edit, :update]

  # 掲示板トップ
  get 'bbs' => 'bbs#index'
  resources :topics do
    resources :posts
  end

  # リンクメニュー
  resources :links, only: [:index, :new, :create, :update, :destroy]
  get   'links/edit'          => 'links#edit', as: :edit_links
  patch 'links/:link_id/sort' => 'links#sort', as: :link_sort

  # 会員登録・ログイン・ログアウトなど
  resources :sessions, only: [:new, :create, :destroy]
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # password resets
  resources :password_resets, only: [:new, :create, :edit, :update]

  # 会員登録
  get  'sign_up'      => 'sign_up#new'
  post 'sign_up'      => 'sign_up#create'
  get  'registration' => 'registration#edit'
  post 'registration' => 'registration#update'

  # メールアドレスの確認
  get  'activation/:id' => 'registration#activation',     as: :activation

  # 入会承認/却下
  get 'approbation/:id' => 'account_approbation#approve', as: :approbation
  get 'rejection/:id'   => 'account_approbation#reject',  as: :rejection

  # 称号保持者
  resources :title_holders

  # letter_opener_web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/laboratory_controller.rb
class LaboratoryController < ApplicationController
  # 研究会トップページ
  def index
  end

  # コメント付き棋譜
  def comment_kifu
  end

  # 将棋上達法
  def gather
  end

  # 四間飛車講座
  def four_file_rook
    render template: 'laboratory/lecture/four_file_rook'
  end

  # 右玉講座
  def right_king
    render template: 'laboratory/lecture/right_king'
  end

  # 旧研究用掲示板
  def old_bbs
  end

  # 特別IDとは
  def special_id
  end

  # 特別IDの使い方
  def special_id_usage
  end

  # 直通チャット
  def direct_chat
  end

  # 以下、研究会トップページ内よりリンク
  # 指定局面戦
  def particular_positions
  end

  # やまもと流右四間講座
  def migishiken
  end

  # 研究会の概要
  def outline
  end
end

app/views/laboratory/comment_kifu.html.slim
- provide :title, 'コメント付棋譜'

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }

h1 コメント付棋譜
p.small.text-right
  | H17年11月8日更新

table.table.table-hover.sortable
  thead
    tr
      th 棋戦名
      th 対局日
      th 対局者（先手）
      th 対局者（後手）
      th 戦型
  tbody
    tr
      th = link_to '第1回新人王戦　決勝第三局', kifu_path(345)
      td 05/10/23
      td hagitarou
      td tanaka90
      td
    tr
      th = link_to '第1回新人王戦　決勝第二局', kifu_path(344)
      td 05/10/19
      td tanaka90
      td hagitarou
      td
    tr
      th = link_to '第1回新人王戦　決勝第一局', kifu_path(343)
      td 05/10/14
      td hagitarou
      td tanaka90
      td
    tr
      th = link_to '第1回王位戦　決勝第二局', kifu_path(342)
      td 05/08/31
      td gagagagaga(上手)
      td saiiti(下手)
      td
    tr
      th = link_to '第1回王位戦　決勝第一局', kifu_path(341)
      td 05/08/28
      td gagagagaga(上手)
      td saiiti(下手)
      td
    tr
      th = link_to '第1回王座戦　決勝第二局', kifu_path(340)
      td 05/03/01
      td nukesaku.
      td yamamoto2.
      td ▲ゴキゲン中飛車 △右四間穴熊
    tr
      th = link_to '第1回王座戦　決勝第一局', kifu_path(339)
      td 05/02/26
      td nukesaku.
      td yamamoto2
      td ▲ゴキゲン中飛車 △右四間穴熊
    tr
      th = link_to '第1回王座戦　準決勝', kifu_path(338)
      td 05/02/24
      td inudanuki
      td nukesaku.
      td ▲四間飛車 △斜め棒銀

p.text-center.mt-4
  | コメント付き棋譜は、５JK棋戦の決勝にあたる対局を対象に、両対局者にコメントしてもらったものです。
  br
  | コメント投稿依頼は対局前に、掲示板やメールなどで運営局からお願いいたします。

app/views/laboratory/direct_chat.html.slim
- provide(:title, '直通チャットの使用方法')

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }
  h5:first-letter {
    color: blue;
  }
  blockquote p {
    font-size: 1rem;
  }
  li {
    padding-bottom: 1rem;
  }

h1
  | 直通チャットの使用方法
p.text-right.text-info
  | 平成17年5月9日更新

h5
  | ■ 直通チャットとは何か？

p
  | 次の画像を見てください。
  br
  | 大きい赤枠がチャットの様子です。小さい赤枠は、今、直通になっている相手のHNです。
  .ml-5
    = image_tag 'special_id/chat_sample.jpg', class: 'img-fluid'
  blockquote
    p
      | Excelsior=&=Marius_P.>　こんばんは〜
      br
      | Marius_P.=&=Excelsior>　これから対局してもらえますか？
      br
      | Excelsior=&=Marius_P.>　はい、お願いしますm(__)m
  | の３行が直通部分で、直通になっていない人には見えません。
  br
  | =&= のマ−クが入っている行が直通を表しているわけです。
  br
  | したがってこの場合、ExcelsiorさんとMarius_p.さん以外の人には、間の３行が抜けて、
  blockquote
    p
      |  kakugyou>　ほうほう
      br
      |  kakugyou>　ちゃまさんがあぶないですね
  | だけが見えているのです。
  br
  |  このように直通チャットは、
  br
  b.ml-4
    | 話を聞かせたい人と聞かせたくない人を分けてチャットができる
  br
  | ので、リレー対局の作戦の話し合いなどに使われます。
  br
  |  もちろんその他の理由で、特定の人に会話を見せたくない時にも使われますが、それはここでは略します。

h5
  | ■ 直通チャットの手順

p
  | では手順を詳しく説明していきます。
  ol.ml-3
    li
      | 下図のように、①観戦者ボタンをクリックします。すると ②の観戦者ダイアログ(小さな画面)が開きます。
      = image_tag 'special_id/chat_1-2.jpg', class: 'img-fluid'
    li
      | 観戦者ダイアログの中に並んでいるＨＮ(ハンドルネーム)の中から、直通(発信)にしたい人を選んでダブルクリックします（→図の④）。
      br
      | すると、=&= マークがＨＮの先頭に付いて、直通状態になりました。
      = image_tag 'special_id/chat_3-5.jpg', class: 'img-fluid'
      br
      | =&= の表示と同時に、プルダウン・メニュー(▼を押すと開く→図⑤が現れます。
      br
      |  ここにはこの例では次の二つの項目が出ます。
      ol
        li.pb-0
          | Marius_P.さん・・・・・・・・・・直通相手です。直通会話は他の人には見えません。
        li.pb-0
          | 「皆へ」・・・・・・・・・・・・・・全員への発信です。観戦者全員に書き込んだメッセージが見えます。
      | この２つを切り替えて、直通か全員への発信かを切り替えることができます。
      br
      | 直通をくれている人の一覧(受信)は、図の③の欄に出ます。
      br
      | この例では空白なので、こちらから先に直通で話しかけようとしています。
    li
      | 直通する相手の人は一度に何人でも指定できます。
      br
      | 例えば下図の⑥では一度に３人を選択しています。
      br
      | ⑦の部分には、今、直通にしている合計人数が３と表示されています。
      = image_tag 'special_id/chat_6-7.jpg', class: 'img-fluid'
    li
      | ここまで設定が済んだら、直通チャットができるようになりました。
      br
      | 下図ではExcelsiorさんとMarius_P.さんが直通チャットをしています。
      = image_tag 'special_id/chat_sample.jpg', class: 'img-fluid'
    li
      | 直通を解除したい時は、解除したいＨＮの上でダブルクリックして =&= マークを外します(図の⑧
      br
      | さらに別なＨＮに直通設定をすれば、直通の切り替えができます。
      = image_tag 'special_id/chat_8-10.jpg', class: 'img-fluid'
      br
      | ⑨の部分には =&= マークがまだ付いていますが、これは向こう側から受信だけ直通になっていることを意味します。
      br
      |  つまりこの例では Marius_P. → Excelsior の方向だけの直通状態になっています。
      br
      |  直通を解除したので⑩には直通チャットの行がありません。最後の行の、
      blockquote
        p
          | Excelsior>　お疲れ様です〜
      | は観戦者全員に見えている普通のチャットにもどりました。

app/views/laboratory/index.html.slim
scss:
  body {
    background-image: url('images/wallppr072.gif');
  }
  table {
    // width: 650px;
    border: 1px solid black;
    border-collapse: separate;
    margin: auto;
    margin-top: 2rem;
  }
  td {
    width: 50%;
    border: 1px solid black;
    padding-left: 1rem;
  }

table
  tr
    td style="vertical-align: top;"
      / img src="../assets/images/logo.jpg" width="324" height="78" alt="五級位上昇を目指す会"
      h1.text-center.mt-3
        | 5JK研究会
      .text-right
        span.small
          | since H17.04.09
      .text-left
        | 更新履歴 
      textarea cols="40" rows="10"
        = "四間飛車講座　追加しました。(H25.12.12)\n右玉講座　　　追加しました。(H28.02.05)".html_safe
    td.text-center
      = image_tag 'particular_positions/shitei2'
      br
      | 第２回指定局面図
  tr
    td colspan="2" style="vertical-align: center"
      p.small.text-center.m-3
        |  当ページは２４サークル「五級位上昇を目指す会」にて密かに（？）活動している、5JK研究会のホームページです。
        br
        | 活動内容は主に、１．指定局面戦、２．棋譜の検討が中心となっています。只今参加者募集中です！
  tr
    td colspan="2" style="text-align:center;font-weight:bold"
      | ＭＥＮＵ
  tr
    td
      = link_to '研究会 (指定局面戦)', laboratory_particular_positions_path
      br
      |  ・第２回研究会  
      br
      |  ・第１回指定局面戦
    td
      = link_to 'コメント付き棋譜', laboratory_comment_kifu_path
  tr
    td
      = link_to '研究用掲示板', topic_path(55)
      br
      = link_to '旧研究用掲示板', laboratory_old_bbs_path
    td
      | 棋譜アップローダ
  tr
    td
      = link_to 'やまもと流右四間講座', laboratory_migishiken_path
    td
      |  常任研究員
  tr
    td
      |  MAT_FIBER講師による 四間飛車講座
      br
      small
        | 例会で行われた四間飛車講座をまとめたものです。
      ul
        li
          = link_to '対居飛車急戦', laboratory_four_file_rook_path
          | (H25.04.20)
        li
          | 対居飛車穴熊
          |  (H25.04.27)
      |  saiiti講師による 右玉講座
      br
      small
        | 例会で行われた右玉講座をまとめたものです。
      ul
        li
          a href="lecture/migi.html"
          = link_to '右玉講座', laboratory_right_king_path
          | (H27.08.01)
    td
      = link_to '研究会の概要', laboratory_outline_path

app/views/laboratory/migishiken.html.slim
- provide :title, 'やまもと流右四間講座＋α'

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }

h1
  | やまもと流右四間講座＋α

p.text-center
  | これは、以前yamamoto2さんがメイン掲示板に書かれていた、
  br
  | 右四間講座をまとめた（むしろ目次をつけたｗ）ものです。
  br
  | 解説は当時と一切変えていません。

.card.m-4
  .card-header
    | 序盤ダイジェスト編
  .card-body
    ul.list-unstyled
      li その１・・・ 中飛車
      li その２・・・ 強気棒銀
      li その３・・・ 升田式石田流ダイジェスト

.card.m-4
  .card-header
    | 右四間飛車講座
  .card-body
    ul.list-unstyled
      li その４・・・ 舟囲い急戦対四間飛車
      li その５・・・ 四間飛車側超急戦の対策
      li その６・・・ 対四間→三間振りなおし作戦
      li その７・・・ 三間飛車対策最新版
      li その８・・・ 早石田対策
      li その９・・・ 対居飛車矢倉対策
      li その１０・・ 矢倉での右四間対策
      li その１１・・ 中飛車対策１
      li その１２・・ 中飛車対策２
      li その１３・・ 雁木対策

p.small.text-right
  | 注: 棋譜プレーヤーで、解説が書かれておりましたが、残念ながらリンク切れです。(H28.2.5追記)

app/views/laboratory/outline.html.slim
- provide :title, '5JK研究会の概要'

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }

h1 研究会の概要

.card.m-4.border.border-info.rounded
  .card-body
    | 　当研究会は将棋倶楽部２４サークル、
    b
      | 「五級位上昇を目指す会」
    | の研究会です。
    br
    | 決して、かの白装束集団みたいに「スカラー電磁波」のようなものは研究しません（笑）

.card.m-4
  .card-body
    h5.card-title
      | 一．当研究会の目的
    p.card-text
      | 当研究会の目的は以下の通りです。
      ol
        li
          | 一つの局面に集中し、研究成果を自分のものにすること
        li
          | 会員同士の交流を図ること
        li
          | 棋譜を検討することにより「手筋」や「感覚」を身に付けること
        li
          | 研究会を通して改めて「将棋の楽しさ」を感じる

.card.m-4
  .card-body
    h5.card-title
      | 二．活動内容
    p.card-text
      | 　当研究会は主に以下の活動を行います。
      ol
        li
          | ある局面での指定局面戦を行う
        li
          | 棋譜を投稿し、局面ごとの最善手の探求や形勢判断を行う
        li
          | 会員間での対局を活発に行い、感想戦も行う
      small
        | また、指定局面戦の準備等は各自で行ってください。

.card.m-4
  .card-body
    h5.card-title
      | 三．参加資格
    p.card-text
      | 基本的に
      b
        u
          | 5JKの会員（卒業生も含む）で、志を持った方であればどなたでも
      | 参加できます。

.card.m-4
  .card-body
    h5.card-title
      | 四．常任研究員について
    p.card-text
      del
        | 常任研究員とは、研究会の出席率が高く、かつ研究会に協力してくださる方のことを示します。
        br
        | 　常任研究員は自ら立候補するか、あるいは常任研究員（もしくは役員）からの推薦でなることができます。また、常任研究員に定員数はございません。
      small
        | (05/04/30 廃止)

.card.m-4
  .card-body
    h5.card-title
      | 五．棋譜掲載について
    p.card-text
      | 研究会の対局は、研究会 Webサイト にて掲載いたします。
      br
      | これは、あくまでも後の研究の為に使用するものです。ご理解・ご協力をお願いいたします。

.card.m-4
  .card-body
    h5.card-title
      | 六．研究会の対局について
    p.card-text
      | 指定局面戦での対局するＨＮは以下の通りでお願いいたします。
      ul
        li
          | 例会で運営委員が組み合わせた対局をする場合・・・ご自分のＨＮを使用してください。（名簿に登録されているＨＮでお願いします）
        li
          | 個々で日程調整し対局する場合・・・特別ＩＤを使用してください。（使用の際、掲示板に一言書き込んでいただければ幸いです）
      | また、研究会では
      b
        u
          | 必ず感想戦を行ってください。
      | 感想戦途中で接続が切れたなど、やむを得ず感想戦が出来なかった場合は掲示板などで行うようにしてください。

.card.m-4
  .card-body
    h5.card-title
      | 更新履歴
    p.card-text
      | ・05/04/30　４項廃止
      br
      | ・05/04/09　β版作成

app/views/laboratory/particular_positions.html.slim
- provide :title, "研究会 指定局面戦"

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }


h1
  | 研究会＆指定局面戦

.card.mb-4
  .card-header
    | 第２回指定局面戦
  .row
    .col-5
      .card-body.text-center
        h5.card-title
          | ゴキゲン中飛車超急戦
        p.card-text
          = image_tag('particular_positions/shitei2')
    .col-7
      .card-body
        p.card-text
          | アンケートで希望が多かったので、ゴキゲン中飛車の超急戦になりました。
          br
          | プロでも避ける、ゴキゲン中飛車で最も激しい変化図です。
          br
          | 今回は▲７五角（堀口弘新手）以下の攻防に絞って検討します。
          br
          br
          = link_to '検討棋譜', kifu_path(346)
          br
          br
          b
            | ★只今参加者受付中！

.card.mb-4
  .card-header
    | 第１回指定局面戦
  .row
    .col-5
      .card-body.text-center
        h5.card-title
          | ▲居飛車急戦vs.△四間飛車
        p.card-text
          = image_tag('particular_positions/shitei1')
    .col-7
      .card-body
        p.card-text
          | 4月2日の例会で行われた、第１回指定局面戦。
          br
          | 後手番四間飛車に先手は急戦で挑もうとする局面だ。
          br
          | ここから、棒銀・４五歩早仕掛け・斜め棒銀・５筋位取りといった戦形から、富沢キックやポンポン桂といった、マイナー戦法へも発展するが・・・。
          ol
            li
              | nukesaku.（居）対Trombone（四）
              | ・・・棒銀
            li
              | yos4460（居）対sasadango（四）
              | ・・・早仕掛け
            li
              | inudanuki（居）対Gnorts（四）
              | ・・・斜め棒銀
            li
              | yamamoto2（居）対Excelsior（四）
              | ・・・棒銀
          p.small.text-right
            | 注: 棋譜プレーヤーで、解説が書かれておりましたが、残念ながらリンク切れです。(H30.2.19追記)

app/views/laboratory/special_id.html.slim
- provide(:title, '特別ＩＤとは')

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }

h1.mb-5
  | 5JK特別ID

.mx-auto style="width: 50%;"
  p.text-center.border.border-info.rounded.p-3.m-3
    |【リレー（兼指定局面戦）用】・・・
    span.text-info
      | $5JK_01 /
      | $5JK_02
h3
  | 使用目的
p.ml-3
  | 研究会やサークル棋戦や他サークルとの交流戦のリレー将棋、指定局面戦を行う場合に使用します。

h3.mt-5
  | 使用方法
p.ml-3
  | 画像付きのくわしい解説
  ul.list-unstyled.ml-5
    li = link_to '特別ＩＤの使用法', laboratory_special_id_usage_path
    li = link_to '直通チャットの使用方法', laboratory_direct_chat_path

h3.mt-5
  | 注意事項
p.ml-3
  |  会員なら、どなたでも使用できます。ただし、
  b
    | 以下の注意事項に同意する必要があります
  | 。
ol
  li
    | パスワードは責任を持って管理すること。関係者以外に安易にパスワードを教えないこと。
  li
    | 特別IDの不正使用は絶対行わないこと。
  li
    | 公の場に、パスワードを絶対公表しないこと。
|  ※もしパスワードを伝え合う場合は、
b
  u
    | 必ず直通チャットで
| 行なってください。

h4.mt-5
  | 更新履歴
ul.list-unstyled.ml-5
  li
    | 12/07/01　研究用ID、使用許可に関する記述を削除
  li
    | 11/10/12　リンク修正
  li
    | 05/05/09　「直通チャットの使用方法」をリンク
  li
    | 05/05/08　「特別IDの使用法」をリンク
  li
    | 05/03/02　特別ID取得、使用方法発行

app/views/laboratory/special_id_usage.html.slim
- provide(:title, '特別ＩＤの使用法')

scss:
  body {
    background-image: url('../images/wallppr072.gif');
  }
  h5:first-letter {
    color: blue;
  }

h1
  | 特別ＩＤの使用法
p.text-right.text-info
  | 平成17年5月8日更新


h5
  | ■ 全体の流れはだいたい次のようになります。(リレー練習の場合)

p
  | 大まかな流れをまずつかんでください。
  ol.ml-3
    li 現ＩＤをいったん退場
    li 特別ＩＤでログイン
    li 普通に対局開始
    li 30手になったら「中断」ボタンを押す(警告が出るのでOKを押す)
    li 直通で作戦タイム(5分程度)
    li 特別IDを退場し、次の人と交代する
    li 以上を対局終了まで繰り返す
    li 局後の感想戦をする

h5
  | ■ 特別IDでのログイン方法
p
  | では詳しく説明していきます。

  ol.ml-3
    li
      | 今ログインしているＩＤ（例えばExcelsiorなど普通のＩＤ）をいったん
      b 退場する
    li
      | あらためて「入場受付」ボタンを押して、ダイアログ（小さな画面）を出します
      = image_tag 'special_id/login.jpg', class: 'img-fluid'
    li
      | 使用する特別ＩＤ(
      b $5JK_01
      |  /
      b $5JK_02
      | )とパスワードを入れます
      br
      | ここでは
      b $5JK_02
      | を使って説明します。

      | 注意点
      ol.ml-3
        li
          | ゲストにしてはいけません。必ず
          b 会員にチェック
          | してください。
        li
          | 「ユーザー名とパスワードを保存」はチェックを外した方がよいでしょう。
        li
          p.mb-0
            | 特別ＩＤとパスワードは
            b 半角英数
            | で、入力してください。
            br
            | 次は良い例です。
            br
            | （○） $5JK_02
            br
            | （○） $5jk_02　・・・・・・・・・・・英字は小文字でもOKです。
            br
            | 次は悪い例。
            br
            | （×） $5JK-02　・・・・・・・・・・ダッシュではダメ。
            br
            | （×） $5JK＿02　・・・・・・・・・
            b アンダーバー（下棒）
            | を半角にしないとダメ。
            br
            | （×） ＄5JK_02　・・・・・・・・・$マークが全角なのでダメ。（わかりずらい(^_^;)）
        li
          | アンダーバー（下棒）の文字「 _ 」は、キーボ−ドの右下にある「ろ」のキーを使います。
          br
          | Shiftキーを押しながら「ろ」を押すとアンダーバーになります。
        li
          | ドルマーク「 $ 」は Shift ＋ ４ のキーを押すと入れられます。
        li
          | ＩＤ、パスワードの入力は、
          b 半角英数モード
          | で行う必要があります。
          br
          | 日本語モードでは入力できないか、全角文字になってしまいます。(^_^A;)アセアセ
    li
      | 入力が完了したら「ログイン」ボタンをクリックします。
    li
      | 次のように「貴方のＨＮ」が出れば、あなたは特別ＩＤでログインできました。
      = image_tag 'special_id/login_completion.jpg', class: 'img-fluid'
    li
      | 次にいつも通りに、ＲかＴかｆｒｅｅの対局室に入ります。どれに入るかは、その時の指示に従ってください。
      br
      | あとはふつうのご自分のＩＤの時と同じように、「挑戦」して対局して行きます。

h5
  | ■ 交代のしかた (30手交代の場合)
ol.ml-3 start='7'
  li
    | お互いの合計手数が 15 + 15 = 30 手になったら、その時点で 30 手目を指した方が「
    b
      | 中断
    | 」を押します。
    = image_tag 'special_id/suspend.jpg', class: 'img-fluid'
  li
    | 直通で作戦タイム（5分程度）を、必要に応じて取ります。
  li
    |「閉じる」→「再開待！」を確認→OKをクリック、します。
    = image_tag 'special_id/resume.jpg', class: 'img-fluid'
  li
    | 退場ボタンを押して、道場からログアウトします。
  li
    | 次の交代者(2将)が特別ＩＤでログインします。
  li
    | 以上を対局終了まで、1将→2将→3将→4将→1将→2将・・・と繰り返します。